### ISSUE TITLE
Adding --build-arg to seihon?

### ISSUE THREAD

**Issue by andig** [ldez/seihon#10]
I need to pass some build args to `docker build` for multi-stage builds, either as `ARG` or as `ENV`- can I do that using seihon?

**Comment by ldez** [comment]
Hello,

currently, it's not possible, there are no extra args passed to the `docker build`, the easier for me it's to improve the template system to allow to expand/substitute the env var inside the template by using [sprig](http://masterminds.github.io/sprig/os.html)

Is this solution for you?

**Comment by andig** [comment]
Can't get it to work:

    RUN GOARCH={{ .GoARCH }} GOARM={{ .GoARM }} SECRET={{ env SECRET }} make build

gives:

    Error: template: tmpl.Dockerfile:20: function "env" not defined

If working it would still not be appropriate for passing secrets I'm afraid as it would be echoed in the build log?

**Comment by ldez** [comment]
It's expected :smile: because I have to add the sprig support :wink: 

Give me a few minutes.

**Comment by ldez** [comment]
Now you can try my PR https://github.com/ldez/seihon/pull/11

**Comment by andig** [comment]
That works, perfect. Unfortunately my follow-up problem is still there as the output is now of course visible in the build log, but that's a different issue I guess.

**Comment by ldez** [comment]
If you are using a CI like Travis, the CI will hide the env var value automatically.

**Comment by andig** [comment]
That‘s true, but it won‘t do that for this scenario as it can‘t know its an env var anymore. Sofar I have not found any way to this this securely without resorting to other components like buildkit, additional secrets server or similar. The trick is to expose the ENV var inside the docker build container without actually showing it. If you have an example anywhere where that‘s done I‘d highly appreciate it, thank you!

**Comment by ldez** [comment]
FYI, Travis replaces the values in the logs even if it's not related to the direct use of an env var.

It's a complex thing to hide an element inside the docker build system. The best approach is to not provide this kind of information during the build but at the runtime, I don't have any other solution in mind, sorry.

**Comment by andig** [comment]
@ldez could we revisit this? Having the same features (in my case providing a "nightly" and a "release" build) for straight builds (using `Dockerfile`) and multi-arch (using `tmpl.Dockerfile`) forces me to work with `--build-arg` for the normal `Dockerfile` and `{{ env ... }}` for the `tmpl.Dockerfile`. 

It would be very convenient, if I could minimise the differences between multiple Dockerfiles.

Supporting `--build-arg` as s seihon option would be awesome and improve compatibility with `buildx`.

**Comment by andig** [comment]
Nevermind, thank you. For sake of reference: I've mapped `buildx` `TARGETVARIANT` to `GOARM` same as the `golang` docker image does. This way I can use `buildx` now without need to use seihon anymore. 

Upside is that the `buildx`

    FROM --platform=$BUILDPLATFORM

speeds up the build process as preparatory steps can be cached during cross-compile.

Thanks for the ride!
