### ISSUE TITLE
Multi-arch build using outdated files

### ISSUE THREAD

**Issue by andig** [ldez/seihon#13]
Hi @ldez I'm having a very strange problem recently, namely a new `.go` file is not picked up by the seihon build. 

For example, here's the naked build:

    ❯ docker build .                         
    Sending build context to Docker daemon  152.1MB
    Step 1/29 : FROM golang:1.14-alpine as builder
    ---> 424d62f19476
    Step 2/29 : RUN apk update && apk add --no-cache git ca-certificates tzdata alpine-sdk npm && update-ca-certificates
    ---> Using cache
    ---> 2ca6dfcc4470
    Step 3/29 : WORKDIR /build
    ---> Using cache
    ---> b026f0e18490
    Step 4/29 : COPY go.mod .
    ---> Using cache
    ---> 4bffab4601f3
    Step 5/29 : COPY go.sum .
    ---> Using cache
    ---> 22518775ba07
    Step 6/29 : RUN go mod download
    ---> Using cache
    ---> 4ca6b0d49ab6
    Step 7/29 : COPY Makefile .
    ---> Using cache
    ---> 2ae33f43513f
    Step 8/29 : COPY package*.json ./
    ---> Using cache
    ---> c635c74e4a28
    Step 9/29 : RUN make install
    ---> Using cache
    ---> 864e6957edcc
    Step 10/29 : COPY assets assets
    ---> Using cache
    ---> 6ed5f73a47e6
    Step 11/29 : COPY vue.config.js vue.config.js
    ---> Using cache
    ---> 1f86bf7b8c85
    Step 12/29 : RUN make clean npm
    ---> Using cache
    ---> 6948ab046915
    Step 13/29 : COPY . .
    ---> fa21a160a3f8
    Step 14/29 : RUN ls meter/disc*
    ---> Running in 39f5d9de84cd
    meter/discovergy.go  <----------- new file is picked up
    Removing intermediate container 39f5d9de84cd
    ---> cf9760280c94

Here's the same seihon build for the same folder:

    ❯ make publish-testing                        
    Version: 0.41 2021-01-28_12:36:02
    seihon publish --dry-run=false --template docker/tmpl.Dockerfile --base-runtime-image alpine:3.12 \
            --image-name andig/evcc -v "testing" --targets=arm.v6,amd64
    Sending build context to Docker daemon  152.1MB
    Step 1/26 : FROM golang:1.14-alpine as builder
    ---> 424d62f19476
    Step 2/26 : RUN apk update && apk add --no-cache git ca-certificates tzdata alpine-sdk npm && update-ca-certificates
    ---> Using cache
    ---> 2ca6dfcc4470
    Step 3/26 : WORKDIR /build
    ---> Using cache
    ---> b026f0e18490
    Step 4/26 : COPY go.mod .
    ---> Using cache
    ---> 4bffab4601f3
    Step 5/26 : COPY go.sum .
    ---> Using cache
    ---> 22518775ba07
    Step 6/26 : RUN go mod download
    ---> Using cache
    ---> 4ca6b0d49ab6
    Step 7/26 : COPY Makefile .
    ---> Using cache
    ---> 2ae33f43513f
    Step 8/26 : COPY package*.json ./
    ---> Using cache
    ---> c635c74e4a28
    Step 9/26 : RUN make install
    ---> Using cache
    ---> 864e6957edcc
    Step 10/26 : COPY assets assets
    ---> Using cache
    ---> 6ed5f73a47e6
    Step 11/26 : COPY vue.config.js vue.config.js
    ---> Using cache
    ---> 1f86bf7b8c85
    Step 12/26 : RUN make clean npm
    ---> Using cache
    ---> 6948ab046915
    Step 13/26 : COPY . .
    ---> Using cache
    ---> fa21a160a3f8 <---------------- matching layer id 
    Step 14/26 : RUN ls meter/disc*
    ---> Using cache
    ---> cf9760280c94 <--------------- new file, different layer id
    Step 15/26 : RUN make assets

Although the previous layer id (in fact all previous layer ids) are matching, the result of the next one differs because the new file apparently doesn't exist.

Any idea what might be wrong here?

**Comment by ldez** [comment]
Hi, I don't have any idea because seihon calls the same standard Docker build command as you called manually.
