### ISSUE TITLE
Apple M1: problems in both qemu and virtualisation frameworks on Mac

### ISSUE THREAD

**Issue by andig** [ldez/seihon#16]
With release of Docker on Mac for M1, various users have noticed docker failures on M1 when running foreign arch images. Root cause appear to be problems in both qemu and virtualisation frameworks on Mac. Docker recommends to run native images to circumvent these issues. 

Currently afaikt `seihon` will run an entire multi-stage build in the foreign architecture. Especially using go that is not required as go has perfect cross-compile abilities. **UPDATE** or am I getting this wrong???

I'm proposing to allow adding an indicator to the `RUN` instruction to run that build step natively:

    FROM HOST golang:1.16-alpine as builder

The additional upside to fixing the Docker issues is that the native build steps will be a factor faster than when using virtualisation.

@ldez I hope this is possible. Worst case it might require `seihon` to parse the `Dockerfile` and split it into individual build steps instead of running the multi-step build through Docker at once?

**Comment by ldez** [comment]
First, I see seihon as a tool for CI more than a local tool.

A "fix" only for Apple M1 users because of problems with virtualization frameworks on Mac and that works only for Go, sounds like an edge case.
I want to keep this tool simple, and Apple M1 is not used on CI.

Have you taken a look at buildx (https://docs.docker.com/buildx/working-with-buildx/)?

**Comment by ldez** [comment]
A workaround is to build the binaries before running seihon and use the first build step only to copy binaries.

In all cases, you will have to build/run "foreign" arch images to create multi-arch images.

**Comment by andig** [comment]
> Currently afaikt seihon will run an entire multi-stage build in the foreign architecture. 

Is that even true? Am I over-complicating things?

> A workaround is to build the binaries before running seihon and use the first build step only to copy binaries.

I was hoping to avoid this as it needs additional scripting for getting the arch into the dockerfile for cross-compiling (which seihon already does).

> A "fix" only for Apple M1 users because of problems with virtualization frameworks on Mac and that works only for Go, sounds like an edge case.

Agreed. That's why I was pointing out the performance gain in running those build steps natively that allow it. Faster builds, less wasted resources. This should apply to more than just go (e.g. preprocessing assets etc). 
Thinking about it, parsing `FROM HOST` and "splitting" the Dockerfile may be really complicated. A better approach could be to use something akin to `{{ RuntimeImage }}` for the other images in the build:

    FROM {{ ImageForArch "host" "alpine:3.13" }}

which would result in adding a `ImageForArch` function. If that's thinkable I could try some prototyping.

> First, I see seihon as a tool for CI more than a local tool.

Understood. Happy to close or see if I could do a prototype.

**Comment by ldez** [comment]
I think it's not possible to convert a "stage" of a Docker file into something executable on a host:
https://github.com/ldez/seihon/blob/f25c9c35f83c75268b36e8e50bc88dfa411f413e/tmpl.Dockerfile#L3-L12

Have you taken a look at buildx (https://docs.docker.com/buildx/working-with-buildx/)?

**Comment by andig** [comment]
> Have you taken a look at buildx

Will do, thank you- much appreciated!
