### ISSUE TITLE
Adding multiple tags for single build

### ISSUE THREAD

**Issue by andig** [ldez/seihon#3]
I've noticed that build multiple versions, typically named version plus latest needs to run the full build twice. This is a waste of CI resources and time. It would be nice if instead the `version` parameter would accept an array and
- add multiple tags to the images after build
- create multiple manifests (seems you cannot add more tags to a manifest?)

**Comment by ldez** [comment]
The multiple tags/version support has been added in v0.4.0 :smile_cat:

**Comment by andig** [comment]
Is this done by specifying the Parameter multiple times?

**Comment by ldez** [comment]
Yes and you can also use coma
```
seihon publish -v "$(TAG_NAME)" -v "latest" --image-name ldez/traefik-certs-dumper
```
or
```
seihon publish --versions="$(TAG_NAME),latest" --image-name ldez/traefik-certs-dumper
```
