### ISSUE TITLE
Use --purge when publishing manifest

### ISSUE THREAD

**Issue by andig** [ldez/seihon#8]
In https://stackoverflow.com/questions/61473753/why-does-docker-use-outdated-latest-when-working-with-multi-arch-images I've experienced that a multi-arch docker image built by seihon would run an old version when using `latest` instead of `<tag>`.

Reading https://stackoverflow.com/questions/59613303/how-do-i-make-multi-arch-docker-images/59613304 it is recommended to use `--purge` when publishing reused tags.

I've confirmed that that fixes https://github.com/ldez/seihon/issues/6#issuecomment-620222821.

**Comment by andig** [comment]
ping @ldez does this make any sense for you?

**Comment by ldez** [comment]
sorry for the late response, it seems right to add `--purge` to the `push` command.
